### ISSUE TITLE
[Tracker]: The new editor

### ISSUE THREAD

**Issue by Watunder** [Watunder/NEO-DOT#21]
- #22
- #24
- #30 
- #42 
- #44
- #49 
- #64
---
- [ ] Add some editors to the table
- [x] Improve debugging experience
- [ ] Enable the frameless editor window
- [x] Add embed-window mode (_experimental_)
