### ISSUE TITLE
[Tracker]: Rebranding

### ISSUE THREAD

**Issue by Watunder** [Watunder/NEO-DOT#32]
_“Never be mean in anything; never be false; never be cruel.”― **Charles Dickens, David Copperfield**._

---

### Neo Skeuomorphism design style
- [ ] a new font face
- [ ] a set of new icons
- [ ] a new default theme

### Code review
- [x] squash and merge
- [x] format code
- [ ] modernaize code
- [ ] update copyright

### Roadmap
- [ ] introduce Catch2 testing framework
  - #53
- #51 
- learn from [godot-proposals](https://github.com/godotengine/godot-proposals/issues)
  - [ ] redesign the editor UX/UI (multi-window, floating docks)
- [ ] add more out-of-the-box features
- improve the fundamental performance
  - [ ] replace the physics engine
  - [ ] replace the rendering engine

**Comment by Watunder** [comment]
### TODO
- [ ] a set of new icons
